In [1]:
import pandas as pd
import numpy as np
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/ia-hackathonn/SampleSubmission.csv
/kaggle/input/ia-hackathonn/Train (2).csv
/kaggle/input/ia-hackathonn/Test (4).csv


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Importing the dataset

In [3]:
df_train = pd.read_csv('../input/ia-hackathonn/Train (2).csv')
df_test = pd.read_csv('../input/ia-hackathonn/Test (4).csv')

In [4]:
df_train.shape

(2898, 1795)

In [5]:
df_test.shape

(1242, 1793)

In [6]:
df_train.head()

ID  channel_0_timestep_0  channel_0_timestep_1  channel_0_timestep_2  \
0  1826              0.666593             -0.127720              0.030188   
1  1959              1.439036              2.939323              4.450541   
2   688             -6.873479              2.620711              6.368775   
3   765              7.343672             -1.043033              3.394326   
4   610              8.988179              1.338421             -2.789729   

   channel_0_timestep_3  channel_0_timestep_4  channel_0_timestep_5  \
0              0.872432              0.066428             -0.688929   
1              4.889985              2.808758              0.174926   
2             -0.753867              0.504129              8.989532   
3             12.075764              2.094330             -6.726448   
4             -4.878788             -7.294619             -6.117245   

   channel_0_timestep_6  channel_0_timestep_7  channel_0_timestep_8  ...  \
0              0.351763              0.962038              1.171841  ...   
1             -0.264143             -0.265241             -2.430413  ...   
2              6.353325             -0.452068             -1.600631  ...   
3             -2.849046             -2.859351             -3.247879  ...   
4             -3.501986             -3.073579              0.061395  ...   

   channel_13_timestep_120  channel_13_timestep_121  channel_13_timestep_122  \
0                 4.268692                 4.296591                 0.405264   
1                -2.719914                 1.040441                 0.272578   
2                 0.051793                -5.156834               -18.325062   
3                11.696478                 5.142235                -2.881666   
4                 5.989770                 5.809627                 4.878367   

   channel_13_timestep_123  channel_13_timestep_124  channel_13_timestep_125  \
0                -2.827268                -2.004783                 1.276288   
1                 0.103977                 3.468313                 6.880353   
2                 2.098055                17.815147                 0.043855   
3                -3.570459                -4.366352                -4.056002   
4                 3.895410                 0.987760                 0.012008   

   channel_13_timestep_126  channel_13_timestep_127  valence  arousal  
0                 2.222049                 0.158765      5.0      6.0  
1                 8.626653                 9.982868      1.0      7.0  
2                -3.858117                17.348724      1.0      6.0  
3                -1.489292                -2.761847      2.0      8.0  
4                -0.732414                -3.816425      1.0      7.0  

[5 rows x 1795 columns]

In [7]:
v=df_train["valence"]
a=df_train["arousal"]

In [8]:
a.unique()

array([6., 7., 8., 1., 5., 3., 2., 4., 9.])

In [9]:
v.unique()

array([5., 1., 2., 4., 3., 7.])

In [10]:
df_train.columns

Index(['ID', 'channel_0_timestep_0', 'channel_0_timestep_1',
       'channel_0_timestep_2', 'channel_0_timestep_3', 'channel_0_timestep_4',
       'channel_0_timestep_5', 'channel_0_timestep_6', 'channel_0_timestep_7',
       'channel_0_timestep_8',
       ...
       'channel_13_timestep_120', 'channel_13_timestep_121',
       'channel_13_timestep_122', 'channel_13_timestep_123',
       'channel_13_timestep_124', 'channel_13_timestep_125',
       'channel_13_timestep_126', 'channel_13_timestep_127', 'valence',
       'arousal'],
      dtype='object', length=1795)

In [11]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2898 entries, 0 to 2897
Columns: 1795 entries, ID to arousal
dtypes: float64(1794), int64(1)
memory usage: 39.7 MB


In [12]:
Id=df_test["ID"]

In [13]:
df_test.head()

ID  channel_0_timestep_0  channel_0_timestep_1  channel_0_timestep_2  \
0  2649              0.726739              1.326801              0.419562   
1  1897             -2.290174             -1.321119             -4.212674   
2  3973             -0.403232             -1.047966             -0.414630   
3  3038              2.900014              0.531952             -1.543073   
4   494             -3.372348             -1.855444              4.717225   

   channel_0_timestep_3  channel_0_timestep_4  channel_0_timestep_5  \
0              0.362655              1.877844              2.177589   
1             -2.404299              3.280274              5.224883   
2             -1.139564             -3.021573             -1.477372   
3             -2.262296              3.178448              5.404681   
4              1.641804             -8.900145            -11.168015   

   channel_0_timestep_6  channel_0_timestep_7  channel_0_timestep_8  ...  \
0              0.881530             -0.177988             -0.107699  ...   
1              5.204860              3.618460             -2.801359  ...   
2              0.307533              0.156880              0.410522  ...   
3              1.022172              1.415055              2.566809  ...   
4             -9.589520            -12.598769             -9.765525  ...   

   channel_13_timestep_118  channel_13_timestep_119  channel_13_timestep_120  \
0                -4.538226                -6.132041                -4.516711   
1                 0.414722                 3.437341                 2.709642   
2                 3.059209                 0.482465                -0.488242   
3                -1.019735                 1.108618                -1.554358   
4               -12.035542               -12.719938                -9.132347   

   channel_13_timestep_121  channel_13_timestep_122  channel_13_timestep_123  \
0                -4.155573                -6.451481                -5.906953   
1                -4.540618                -8.604247                -8.877815   
2                 2.093967                 0.955976                -1.962847   
3                -6.510234                -8.960296                -3.087777   
4               -10.269296                -6.274572                 1.645681   

   channel_13_timestep_124  channel_13_timestep_125  channel_13_timestep_126  \
0                -1.217648                 2.809138                 5.387832   
1                -5.269321                 4.677503                11.745440   
2                -0.305406                 2.123710                 2.303813   
3                 6.820467                12.740038                12.078416   
4                -2.948617               -10.918031                -5.863556   

   channel_13_timestep_127  
0                 7.240309  
1                11.366855  
2                 1.377429  
3                 2.254736  
4                -1.668832  

[5 rows x 1793 columns]

In [14]:
df_train.drop("ID" , axis=1, inplace=True)
df_test.drop("ID" , axis=1, inplace=True)

Processing missing values

In [15]:
df_train.isnull().sum().sort_values(ascending =False).head(5)

channel_0_timestep_0      0
channel_10_timestep_65    0
channel_9_timestep_51     0
channel_9_timestep_50     0
channel_9_timestep_49     0
dtype: int64

Percentage of missing data

Treatment of left parameters having missing values

Removing the Id column

# Artificial Neural Network

In [16]:
trainn=df_train.drop("valence",axis=1)

In [17]:
trainn

channel_0_timestep_0  channel_0_timestep_1  channel_0_timestep_2  \
0                 0.666593             -0.127720              0.030188   
1                 1.439036              2.939323              4.450541   
2                -6.873479              2.620711              6.368775   
3                 7.343672             -1.043033              3.394326   
4                 8.988179              1.338421             -2.789729   
...                    ...                   ...                   ...   
2893              2.597523             -5.404371             -7.261963   
2894              0.023456             -5.002498             -6.201032   
2895              0.418006              0.489591              0.399380   
2896              2.673160              1.955546              0.872103   
2897            -15.531085            -13.170703            -13.555800   

      channel_0_timestep_3  channel_0_timestep_4  channel_0_timestep_5  \
0                 0.872432              0.066428             -0.688929   
1                 4.889985              2.808758              0.174926   
2                -0.753867              0.504129              8.989532   
3                12.075764              2.094330             -6.726448   
4                -4.878788             -7.294619             -6.117245   
...                    ...                   ...                   ...   
2893             -5.821558             -6.905499             -3.372167   
2894             -0.268211              1.768780             -2.178749   
2895              0.076094             -0.080600              0.114078   
2896             -0.888802             -1.995294             -0.695374   
2897            -17.565762            -16.688934            -10.048054   

      channel_0_timestep_6  channel_0_timestep_7  channel_0_timestep_8  \
0                 0.351763              0.962038              1.171841   
1                -0.264143             -0.265241             -2.430413   
2                 6.353325             -0.452068             -1.600631   
3                -2.849046             -2.859351             -3.247879   
4                -3.501986             -3.073579              0.061395   
...                    ...                   ...                   ...   
2893             -0.098528             -4.118333             -2.304121   
2894              0.325151              7.422237              7.472040   
2895              0.445269              0.719440              0.730063   
2896              1.180189              1.196407              0.016508   
2897             -0.383483             14.014765             28.323889   

      channel_0_timestep_9  ...  channel_13_timestep_119  \
0                 2.323957  ...                 1.378793   
1                -4.575553  ...                -6.864929   
2                -5.637474  ...               -14.872344   
3                 3.040648  ...                 6.079260   
4                 6.580954  ...                 1.013592   
...                    ...  ...                      ...   
2893              2.807478  ...               -11.493681   
2894              4.527164  ...                 0.105220   
2895              0.520684  ...                 0.971298   
2896             -1.190031  ...                -5.766486   
2897             38.613426  ...                 8.686493   

      channel_13_timestep_120  channel_13_timestep_121  \
0                    4.268692                 4.296591   
1                   -2.719914                 1.040441   
2                    0.051793                -5.156834   
3                   11.696478                 5.142235   
4                    5.989770                 5.809627   
...                       ...                      ...   
2893                -8.553452                -4.326558   
2894                -0.876480                 1.165987   
2895                 2.296222                 2.376399   
2896                -6.545377         

In [18]:
trainn=trainn.drop("arousal" , axis=1 )

In [19]:
trainn.shape

(2898, 1792)

In [20]:
X_train = np.array(trainn)
y_train = np.array(df_train[["valence","arousal"]])
X_test = np.array(df_test)

In [21]:
print('Shape of X_train {} \nShape of y_test {}\nShape of X_test {}'.format(X_train.shape,y_train.shape,X_test.shape))

Shape of X_train (2898, 1792) 
Shape of y_test (2898, 2)
Shape of X_test (1242, 1792)


#### Feature Scaling

In [22]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
X_train = mms.fit_transform(X_train)
X_test = mms.transform(X_test)

In [23]:
y_train

array([[5., 6.],
       [1., 7.],
       [1., 6.],
       ...,
       [5., 5.],
       [4., 7.],
       [1., 7.]])

In [24]:
y_train = mms.fit_transform(y_train.reshape(-1,2))

In [25]:
y_train

array([[0.66666667, 0.625     ],
       [0.        , 0.75      ],
       [0.        , 0.625     ],
       ...,
       [0.66666667, 0.5       ],
       [0.5       , 0.75      ],
       [0.        , 0.75      ]])

In [26]:
from keras.models import Sequential
from keras.layers import Dense,Dropout

In [27]:
# regressor = Sequential()
# regressor.add(Dense(units=512,activation='relu',kernel_initializer='uniform'))
# regressor.add(Dense(units=256,activation='relu',kernel_initializer='uniform'))
# regressor.add(Dense(units=128,activation='relu',kernel_initializer='uniform'))
# regressor.add(Dense(units=64,activation='relu',kernel_initializer='uniform'))
# regressor.add(Dense(units=2,activation='relu',kernel_initializer='uniform'))

In [28]:
# regressor.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mean_absolute_error'])

In [29]:
# regressor.fit(X_train,y_train,epochs=250,batch_size=15)

In [30]:
# losses = regressor.history.history
# losses = np.array(pd.DataFrame(losses))
# plt.plot(losses)
# plt.xlabel('Epochs')
# plt.ylabel('loss')

In [31]:
# y_pred = regressor.predict(X_test) 
# y_pred_original = mms.inverse_transform(y_pred.reshape(-1,2))
# y_pred_original = y_pred_original.tolist()

In [32]:
# x=[i[0] for i in y_pred_original]
# y=[i[1] for i in y_pred_original]

In [33]:
# df=pd.DataFrame({"ID":Id,"x":x,"y":y})

In [34]:
# sub1=df.to_csv("sub3.csv", index=False)

****

****

In [35]:
from sklearn.linear_model import ElasticNet, Lasso,  BayesianRidge, LassoLarsIC
from sklearn.ensemble import RandomForestRegressor,  GradientBoostingRegressor
from sklearn.kernel_ridge import KernelRidge
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.base import BaseEstimator, TransformerMixin, RegressorMixin, clone
from sklearn.model_selection import KFold, cross_val_score, train_test_split
from sklearn.metrics import mean_squared_error
import xgboost as xgb
import lightgbm as lgb

In [36]:
#Validation function
n_folds = 5

def mae_cv(model):
    kf = KFold(n_folds, shuffle=True, random_state=42).get_n_splits(X_train)
    mae= (-cross_val_score(model, X_train, y_train, scoring="neg_mean_absolute_error", cv = kf))
    return(mae)

In [37]:
lasso = make_pipeline(RobustScaler(), Lasso(alpha =0.0005, random_state=1))